### ISSUE TITLE
Add table fail on onUpgrade

### ISSUE THREAD

**Issue by JulienDev** [foxykeep/ContentProviderCodeGenerator#10]
Imagine we have a database with current database version 4.
Let's add a table called "Tabs" on database version 5.

``` javascript
{
            "table_name":"Tabs",
            "version":5,
            "fields":[
                {
                    "name":"id",
                    "type":"long",
                    "is_primary_key":true,
                    "is_id":true
                        },
                {
                    "name":"name",
                    "type":"text"
                }
            ]
        }
```

The code generated is the following  : 

``` java
// Version 6 : Creation of the table
        public static void upgradeTable(SQLiteDatabase db, int oldVersion, int newVersion) {

            if (oldVersion < 1) {
                Log.i(LOG_TAG, "Upgrading from version " + oldVersion + " to " + newVersion 
                        + ", data will be lost!");

                db.execSQL("DROP TABLE IF EXISTS " + TABLE_NAME + ";");
                createTable(db);
                return;
            }


            if (oldVersion != newVersion) {
                throw new IllegalStateException("Error upgrading the database to version " 
                        + newVersion);
            }
        }
```

The SQLiteOpenHelper with its method getDatabaseLocked detects a new version and then launches "onUpgrade(db, version, mNewVersion);. 

Tabs.upgradeTable(db, oldVersion, newVersion); is called, oldVersion=4 and newVersion=5 so the first condition is false and the second is true and we throw an exception. Shouldn't we add a mechanism to force the table creation? 

Julien

**Comment by frapontillo** [comment]
This is an issue I have as well.
I haven't quite understood the upgrade mechanism, why is there the `if (oldVersion < 1)` check? Shouldn't it simply check if the new table version is higher than the older one, and if so create the table?

**Comment by frapontillo** [comment]
Is there any update on this? The generator basically has no way of adding new tables in newer versions.

**Comment by frapontillo** [comment]
I _may_ have found a fix: https://github.com/frapontillo/ContentProviderCodeGeneratorPlus/commit/7b49c016298077b8cba2576bd1cf41b9af77300c

The comparison between the `oldVersion` has to be done against the new table version, not a fixed number. I have tested it in a project of mine and it seems to be working. Will submit a PR.

**Comment by JulienDev** [comment]
Something like that? https://github.com/foxykeep/ContentProviderCodeGenerator/pull/3

**Comment by frapontillo** [comment]
Yeah, but the comparison shouldn't be done against `newVersion` (which is the database version) but the new version of the table (that, in some cases, may equal the db version).

**Comment by foxykeep** [comment]
Working on it. (sorry work is crazy currently so I don't have a lot of time to work on my open source projects ...)

Trying to have a fix by tonight

**Comment by JulienDev** [comment]
Thank you Nicolas ;)

**Comment by frapontillo** [comment]
Great! :D
