### ISSUE TITLE
Making a JOIN query over a content provider generated by this tool

### ISSUE THREAD

**Issue by suarezjulian** [foxykeep/ContentProviderCodeGenerator#17]
Hi, 

First of all thank you so much for this, it has been great, I really like using this together with dataDroid.

Now usually when you need to perform a query with a JOIN on  your content provider you need to setup a new Uri on your URI matcher to "catch" the query correctly and route your code accordingly.

As of right now I'm unable to find support for this on this tool, so how would you suggest to do this?, maybe supporting this on the tool itself or changing the generated code afterwards.

**Comment by frapontillo** [comment]
It is possible, just extend the generated ContentProvider and use that, set up new Uris and make your queries there.
