### ISSUE TITLE
autoincrement on long

### ISSUE THREAD

**Issue by jbarwick** [foxykeep/ContentProviderCodeGenerator#22]
I'm a newbie to SQLite.  So please forgive.  But I did receive this error:

Exception in thread "main" java.lang.IllegalArgumentException: Field "eventId" | is_autoincrement can only be used on an integer type field
    at com.foxykeep.cpcodegenerator.model.FieldData.<init>(FieldData.java:44)
    at com.foxykeep.cpcodegenerator.model.TableData.<init>(TableData.java:40)
    at com.foxykeep.cpcodegenerator.model.TableData.getClassesData(TableData.java:66)
    at com.foxykeep.cpcodegenerator.Main.main(Main.java:100)

I changed the code on line 44 to 

if (dbIsAutoincrement && !type.equals("integer") && !type.equals("long")) {
                throw new IllegalArgumentException("Field \"" + name + "\" | is_autoincrement can "
                        + "only be used on an integer type field");
            }

My question is...is autoincrement valid only on int types?  Is long OK?

**Comment by frapontillo** [comment]
`AUTOINCREMENT` is only valid on integers: http://www.sqlite.org/autoinc.html

**Comment by jbarwick** [comment]
that was fast....thanks.

**Comment by writtmeyer** [comment]
You should know that SQLite only knows about the datatype "integer" and doesn't have the datatype "long". AFAIK SQLite changes any CREATE TABLE statement containing long types to integers anyway:

http://www.sqlite.org/datatype3.html

SQLite is very flexible and adapts to the actual data (the definition in CREATE TABLE is not that importantas in other relational databases). So inserting a long value into a integer column works fine.

**Comment by foxykeep** [comment]
Wolfram is right. My code is actually changing Java longs into SQLite
integers IIRC.

Nicolas KLEIN aka Foxykeep

**Comment by jbarwick** [comment]
I guess the next question I have is: is a SQLite integer the same size as a java long or a java int.  if it the same size as a java long then my requested code change is valid (auto-increment on a java long)

I guess the question is: are we using the JSON def file just to create a SQLite provider or is this also a way to, one day, auto-generate a data model java class structure.

I was using the mdsd-content-provider-generator which reads an ecore model and attempts to generate both the provider and the model.

It was an interesting exercise, but it's just too incomplete to be very useful when trying to build a model with complex (or even simple) relationships.  An the code is one year old untouched.

So, I am warming up to foxykeep's take on creating a provider (very different than mdsd!!) and creating the data object model manually.  Probably better that way.

Thanks guys.

**Comment by foxykeep** [comment]
AFAIK there is no limit besides the os limit on the size of sqlite
integers. I've been saving java long into sqlite integers forever. So it
should work.

Nicolas Klein aka Foxykeep
