### ISSUE TITLE
NotificationUri should be the one provided by the query

### ISSUE THREAD

**Issue by JulienDev** [foxykeep/ContentProviderCodeGenerator#9]
Hi,

When we do a request, the notificationUri is not the given Uri but the authority Uri. It causes a cursor to be notified each time there is a change somewhere in the database. The notificationUri should be the queried Uri.

Current source generated :

Uri notificationUri = LeGorafiContent.CONTENT_URI;
[...]
if ((c != null) && !isTemporary()) {
       c.setNotificationUri(getContext().getContentResolver(), notificationUri);
}

Julien

**Comment by frapontillo** [comment]
I had the same issue, so I forked the repository and changed the default behavior, please see #7. You can use that and then notify changes as you please. I plan on keeping that fork updated to the latest changes made on the original repository if @foxykeep is not going to accept that PR.
